"""Selective Morse keyboard / Windows X-button input with owned hook lifetime.

Only configured input keys are consumed. Injected events are intentionally
accepted so reWASD mappings work; keyboard's own replay guard bypasses events
generated by this application's keyboard output.
"""

import ctypes
from ctypes import wintypes
from collections import deque
import logging
import platform
import threading
import time

import keyboard
from PyQt5.QtCore import QThread, pyqtSignal


WM_XBUTTONDOWN = 0x020B
WM_XBUTTONUP = 0x020C
WM_QUIT = 0x0012
WH_MOUSE_LL = 14
# If the OS ever refuses to unhook, retain the ctypes callback until process
# exit. Dropping it while Windows still has its address risks an access fault.
_retained_failed_hooks = []


class MSLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [('pt', wintypes.POINT), ('mouseData', wintypes.DWORD),
                ('flags', wintypes.DWORD), ('time', wintypes.DWORD),
                ('dwExtraInfo', ctypes.c_size_t)]


def mouse_button_event(message, mouse_data):
    """Decode only side-button messages; mouse_data stores XBUTTON in HIWORD."""
    if message not in (WM_XBUTTONDOWN, WM_XBUTTONUP):
        return None
    button = (int(mouse_data) >> 16) & 0xffff
    if button not in (1, 2):
        return None
    return 'mouse:x%d' % button, message == WM_XBUTTONDOWN


class WindowsMouseHook:
    """Run one native low-level hook and its message loop in the caller thread.

    stop() is safe from another thread and before registration completes.
    The callback only emits a Qt signal; no GUI or decoding work runs here.
    """
    def __init__(self, selected, callback, active=lambda: True, user32=None, kernel32=None):
        if user32 is None:
            if platform.system() != 'Windows':
                raise RuntimeError('鼠标 X1 / X2 输入目前仅支持 Windows。')
            user32 = ctypes.WinDLL('user32', use_last_error=True)
            kernel32 = ctypes.WinDLL('kernel32', use_last_error=True)
        self.user32 = user32
        self.kernel32 = kernel32
        self.selected = dict(selected)
        self.callback = callback
        self.active = active
        self._stopping = threading.Event()
        self._thread_id = None
        self._hook = None
        callback_factory = getattr(ctypes, 'WINFUNCTYPE', ctypes.CFUNCTYPE)
        self._callback_type = callback_factory(ctypes.c_ssize_t, ctypes.c_int,
                                               ctypes.c_size_t, ctypes.c_ssize_t)
        self._native_callback = self._callback_type(self._handle_native)
        self._configure_api()

    def _configure_api(self):
        signatures = (
            ('SetWindowsHookExW', [ctypes.c_int, self._callback_type, wintypes.HINSTANCE, wintypes.DWORD], wintypes.HANDLE),
            ('CallNextHookEx', [wintypes.HANDLE, ctypes.c_int, ctypes.c_size_t, ctypes.c_ssize_t], ctypes.c_ssize_t),
            ('UnhookWindowsHookEx', [wintypes.HANDLE], wintypes.BOOL),
            ('GetMessageW', [ctypes.POINTER(wintypes.MSG), wintypes.HWND, wintypes.UINT, wintypes.UINT], wintypes.BOOL),
            ('PeekMessageW', [ctypes.POINTER(wintypes.MSG), wintypes.HWND, wintypes.UINT, wintypes.UINT, wintypes.UINT], wintypes.BOOL),
            ('TranslateMessage', [ctypes.POINTER(wintypes.MSG)], wintypes.BOOL),
            ('DispatchMessageW', [ctypes.POINTER(wintypes.MSG)], ctypes.c_ssize_t),
            ('PostThreadMessageW', [wintypes.DWORD, wintypes.UINT, ctypes.c_size_t, ctypes.c_ssize_t], wintypes.BOOL),
        )
        for name, args, result in signatures:
            function = getattr(self.user32, name)
            function.argtypes, function.restype = args, result
        self.kernel32.GetCurrentThreadId.argtypes = []
        self.kernel32.GetCurrentThreadId.restype = wintypes.DWORD
        self.kernel32.GetModuleHandleW.argtypes = [wintypes.LPCWSTR]
        self.kernel32.GetModuleHandleW.restype = wintypes.HMODULE

    def _handle_native(self, code, message, address):
        if code >= 0 and not self._stopping.is_set() and self.active():
            try:
                # Read lParam only for messages whose structure we consume.
                if message in (WM_XBUTTONDOWN, WM_XBUTTONUP):
                    data = ctypes.cast(address, ctypes.POINTER(MSLLHOOKSTRUCT)).contents
                    decoded = mouse_button_event(message, data.mouseData)
                    if decoded and decoded[0] in self.selected:
                        key, pressed = decoded
                        self.callback(key, pressed, self.selected[key], time.monotonic())
                        return 1
            except Exception:
                logging.exception('处理鼠标侧键输入失败')
        return self.user32.CallNextHookEx(self._hook, code, message, address)

    def run(self, ready=None):
        message = wintypes.MSG()
        # Force the thread message queue to exist before publishing its ID;
        # otherwise a stop between registration and GetMessage could be lost.
        self.user32.PeekMessageW(ctypes.byref(message), None, 0, 0, 0)
        self._thread_id = self.kernel32.GetCurrentThreadId()
        if self._stopping.is_set() or not self.active():
            self._thread_id = None
            return
        try:
            self._hook = self.user32.SetWindowsHookExW(
                WH_MOUSE_LL, self._native_callback, self.kernel32.GetModuleHandleW(None), 0)
            if not self._hook:
                raise OSError(ctypes.get_last_error(), '无法安装鼠标侧键监听')
            if self._stopping.is_set() or not self.active():
                return
            if ready:
                ready()
            while not self._stopping.is_set() and self.active():
                result = self.user32.GetMessageW(ctypes.byref(message), None, 0, 0)
                if result == -1:
                    raise OSError(ctypes.get_last_error(), '鼠标监听消息循环失败')
                if result == 0:
                    break
                self.user32.TranslateMessage(ctypes.byref(message))
                self.user32.DispatchMessageW(ctypes.byref(message))
        finally:
            if self._hook:
                if not self.user32.UnhookWindowsHookEx(self._hook):
                    self._stopping.set()
                    _retained_failed_hooks.append(self)
                    logging.error('无法释放鼠标侧键监听，已停止处理并保留回调直到程序退出')
                self._hook = None
            self._thread_id = None

    def stop(self):
        self._stopping.set()
        thread_id = self._thread_id
        if thread_id is not None:
            self.user32.PostThreadMessageW(thread_id, WM_QUIT, 0, 0)


class KeyListenerThread(QThread):
    keyEvent = pyqtSignal(str, bool, int)
    timedKeyEvent = pyqtSignal(str, bool, int, float)
    listenerError = pyqtSignal(str)
    listenerReady = pyqtSignal()

    def __init__(self, configured_keys):
        super().__init__()
        self.configured_keys = list(configured_keys)
        self.keep_running = True
        self._mouse_hook = None
        self.error = None
        self._event_lock = threading.Lock()
        self._pending_events = deque()

    def run(self):
        unhooks = []
        try:
            selected_mouse = {}
            for role, key in enumerate(self.configured_keys):
                if not self.keep_running:
                    break
                if key.startswith('mouse:'):
                    if key not in ('mouse:x1', 'mouse:x2'):
                        raise ValueError('不支持的鼠标输入键：' + key)
                    selected_mouse[key] = role
                    continue
                if platform.system() == 'Darwin' and key not in ('shift', 'ctrl', 'alt', 'cmd'):
                    raise ValueError('macOS 输入键仅支持修饰键。')
                callback = lambda event, key=key, role=role: self.on_key_event(event, key, role)
                unhooks.append(keyboard.hook_key(key, callback, suppress=True))
            if selected_mouse and self.keep_running:
                self._mouse_hook = WindowsMouseHook(selected_mouse, self._emit_key,
                                                    active=lambda: self.keep_running)
                self._mouse_hook.run(ready=self.listenerReady.emit)
            elif self.keep_running:
                self.listenerReady.emit()
                while self.keep_running:
                    time.sleep(0.025)
        except Exception as error:
            self.error = str(error)
            self.listenerError.emit(self.error)
            # A QThread exception escaping run() can terminate the process.
            # Direct invocation remains useful for deterministic regression tests.
            if not self.isRunning():
                raise
            logging.exception('启动摩斯输入监听失败')
        finally:
            with self._event_lock:
                self.keep_running = False
                self._pending_events.clear()
            if self._mouse_hook is not None:
                self._mouse_hook.stop()
                self._mouse_hook = None
            for unhook in reversed(unhooks):
                try:
                    unhook()
                except Exception:
                    logging.exception('释放摩斯输入监听失败')

    def _emit_key(self, key, pressed, role, timestamp):
        with self._event_lock:
            if not self.keep_running:
                return
            self._pending_events.append((key, pressed, role, timestamp))
        # Queue before notifying Qt. A timer can also consume this event before
        # the queued signal is delivered; signals are wakeups, not a second copy
        # of the authoritative input stream.
        self.keyEvent.emit(key, pressed, role)
        self.timedKeyEvent.emit(key, pressed, role, timestamp)

    def snapshot_events(self):
        """Return (cutoff, events) from one atomic queue snapshot.

        The GUI consumes every returned event before ticking its engine to
        cutoff, never to a newly sampled later time. Events contain the same
        four values as timedKeyEvent and are returned in observed-time order.
        Each queued event is returned once, including equal-timestamp events.
        OS callbacks only hold this lock to append; GUI work must happen after
        this method returns. An event observed before but enqueued after the
        snapshot is handled by the engine's late-input safety check.
        """
        with self._event_lock:
            cutoff = time.monotonic()
            events = list(self._pending_events)
            self._pending_events.clear()
        return cutoff, sorted(events, key=lambda event: event[3])

    def on_key_event(self, event, key, role):
        if not self.keep_running or getattr(event, 'is_keypad', False):
            return True
        # Retain keyboard's own-output guard, without rejecting reWASD events
        # merely because Windows labels them as injected.
        if getattr(getattr(keyboard, '_listener', None), 'is_replaying', False):
            return True
        sided_names = {
            'left ctrl': ('left ctrl', 'ctrl'), 'right ctrl': ('right ctrl',),
            'left shift': ('left shift', 'shift'), 'right shift': ('right shift',),
        }
        if key in sided_names and event.name not in sided_names[key]:
            return True
        if event.event_type not in (keyboard.KEY_DOWN, keyboard.KEY_UP):
            return True
        try:
            self._emit_key(key, event.event_type == keyboard.KEY_DOWN, role, time.monotonic())
        except Exception:
            logging.exception('处理键盘输入失败')
            return True
        return False

    def stop(self):
        with self._event_lock:
            self.keep_running = False
            self._pending_events.clear()
        if self._mouse_hook is not None:
            self._mouse_hook.stop()
        if self.isRunning() and QThread.currentThread() != self:
            self.wait()
